from enum import Enum


class UnknownValue(str, Enum):
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ReasonCode(str, Enum):
    LOW_RESOLUTION_CONFIDENCE = "LOW_RESOLUTION_CONFIDENCE"
    MISSING_TICKER = "MISSING_TICKER"
    AMBIGUOUS_ENTITY_MATCH = "AMBIGUOUS_ENTITY_MATCH"
    INSTRUMENT_MISMATCH = "INSTRUMENT_MISMATCH"
    DUPLICATE_FILING = "DUPLICATE_FILING"
    AMENDMENT_SUPERSEDED = "AMENDMENT_SUPERSEDED"
    UNSUPPORTED_TRANSACTION_TYPE = "UNSUPPORTED_TRANSACTION_TYPE"
    OCR_PARSE_LOW_CONFIDENCE = "OCR_PARSE_LOW_CONFIDENCE"
    ENTITY_ROLE_EXCLUDED = "ENTITY_ROLE_EXCLUDED"
    NON_SIGNAL_ASSET = "NON_SIGNAL_ASSET"
    MISSING_COUNTERPART = "MISSING_COUNTERPART"
    LOW_SOURCE_CONFIDENCE = "LOW_SOURCE_CONFIDENCE"


class RunStatus(str, Enum):
    STARTED = "STARTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class SourceName(str, Enum):
    INSIDER = "insider"
    CONGRESS = "congress"
    COMBINED = "combined"


class ResolutionStatus(str, Enum):
    RESOLVED = "RESOLVED"
    AMBIGUOUS = "AMBIGUOUS"
    UNRESOLVED = "UNRESOLVED"


class OverlayOutcome(str, Enum):
    ALIGNED_BULLISH = "ALIGNED_BULLISH"
    ALIGNED_BEARISH = "ALIGNED_BEARISH"
    LOW_CONFIDENCE_ALIGNMENT = "LOW_CONFIDENCE_ALIGNMENT"
    TRUE_CONFLICT = "TRUE_CONFLICT"
    BLOCKED_AMBIGUOUS = "BLOCKED_AMBIGUOUS"
    BLOCKED_LOW_CONFIDENCE = "BLOCKED_LOW_CONFIDENCE"
    BLOCKED_INSTRUMENT_MISMATCH = "BLOCKED_INSTRUMENT_MISMATCH"
    SINGLE_SOURCE_ONLY = "SINGLE_SOURCE_ONLY"
